name: Pylint

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        verison: ["3.13.0-alpha.3", "3.12", "3.11", "3.10", "3.9", "3.8", "3.7"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.verison}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.verison}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analyzing the code with pylint
      run: |
        pylint src --rcfile=standard.rc
    - name: Testing usability
      run: |
        wget https://raw.githubusercontent.com/Tumpa-Prizrak/Tumpa-Prizrak/master/plaintext.txt
        echo . >> src/root_folder
        python -m src parse
        python -m src random
        python -m src remove --id 1 --no-confirm
        rm src/root_folder
        rm plaintext.txt
        rm ocs.json
    # rm pylint.txt; pylint src >> pylint.txt
